version: '2'

volumes:
  postgres_data_local: {}
  postgres_backup_local: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app
    environment:
      - POSTGRES_USER=YXwNdcpPnqolLoSJ
      - USE_DOCKER=yes
    ports:
      - "8000:8000"
    command: /start.sh
    container_name: ether

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - postgres_backup_local:/backups
    environment:
      - POSTGRES_USER=YXwNdcpPnqolLoSJ

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"


  redis:
    image: redis:3.0

#  celeryworker:
#    # https://github.com/docker/compose/issues/3220
#    <<: *django
#    depends_on:
#      - redis
#      - postgres
#      - mailhog
#    ports: []
#    command: /start-celeryworker.sh
#
#  celerybeat:
#    # https://github.com/docker/compose/issues/3220
#    <<: *django
#    depends_on:
#      - redis
#      - postgres
#      - mailhog
#    ports: []
#    command: /start-celerybeat.sh

  ganache:
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"
    volumes:
      - ./.ethereum_data:/ethereum_data
    entrypoint:
      - node
      - ./build/cli.node.js
      - -n
      - -a
      - '10'
      - --db=/ethereum_data
